#!/bin/bash
# @File: upload-test-pypi
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-07

./build-package
cp deployment/upload-pypi/config/.pypirc ~/.pypirc
pip install twine
pip install --upgrade twine
twine upload --repository testpypi dist/*

rm -rf austin_module_daily.egg-info build dist
